name: Build & Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Container Apps Extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Set Variables
        run: |
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=entityint" >> $GITHUB_ENV
          echo "ACR_NAME=crentityint${{ github.event.inputs.environment }}001" >> $GITHUB_ENV
          echo "CONTAINER_ENV=env-entityint-${{ github.event.inputs.environment }}-001" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "APP_NAME=entity-api-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Build JAR
        run: ./gradlew clean build

      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/entity-api:$IMAGE_TAG .

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Push Image
        run: |
          docker push $ACR_NAME.azurecr.io/entity-api:$IMAGE_TAG

      - name: Deploy or Update Container App
        run: |
          az containerapp create \
            --name $APP_NAME \
            --resource-group poc-rg \
            --environment $CONTAINER_ENV \
            --image $ACR_NAME.azurecr.io/entity-api:$IMAGE_TAG \
            --target-port 8080 \
            --ingress external \
            --registry-server $ACR_NAME.azurecr.io \
            --min-replicas 0 \
            --max-replicas 1 \
            --cpu 0.5 \
            --memory 1Gi \
          || \
          az containerapp update \
            --name $APP_NAME \
            --resource-group poc-rg \
            --image $ACR_NAME.azurecr.io/entity-api:$IMAGE_TAG \
            --min-replicas 0 \
            --max-replicas 1

      - name: Print API URL
        run: |
          FQDN=$(az containerapp show \
            --name $APP_NAME \
            --resource-group poc-rg \
            --query properties.configuration.ingress.fqdn \
            -o tsv)

          echo "======================================"
          echo "API URL:"
          echo "https://$FQDN"
          echo "======================================"