name: Undeploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  undeploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Container App
        run: |
          az containerapp delete \
            --name entity-api-${{ github.event.inputs.environment }} \
            --resource-group poc-rg \
            --yes